twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        time_slot_service: '@App\Service\TimeSlotService'

when@test:
    twig:
        strict_variables: true
