vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /uploads/images/posters
            upload_destination: ‘%kernel.project_dir%/public/uploads_directory%’
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
